version: 2.1 # Upgrading to 2.1 allows for better features, though 2.0 still works
jobs:
  build:
    docker:
      - image: cimg/node:12.22-browsers 
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: Clean Install
          command: |
            rm -rf node_modules
            npm install
      - run:
          name: Build Project
          command: ./node_modules/.bin/ember build --environment=production
